Repository EndBug/add-and-commit, pull requests merged in 2022-03, with the labels that each got.

#374 feat: add `tag_push` input and `tag_pushed` output
  action.yml
  lib/index.js
  src/io.ts
  src/main.ts
Labels: type: bug

#376 fix!: fail when there's an error while committing
  lib/index.js
  src/main.ts
Labels: type: bug

#378 Add missing single quote
  README.md
Labels: type: docs, good first issue

#380 chore: bump simple-git
  lib/index.js
  package-lock.json
  package.json
  src/main.ts
Labels: type: security
